version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PHP_V=${PHP_V}
    container_name: app-${APP_NAME}
    restart: always
    working_dir: /var/www/
    volumes:
      - /srv/www/${APP_NAME}:/var/www

  nginx:
    image: nginx:1.24-alpine
    container_name: nginx-${APP_NAME}
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - /srv/www/${APP_NAME}:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
      
  code-server:
    build:
      context: ./code-server/
      dockerfile: Dockerfile
      args:
        - PHP_V=${PHP_V}
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - PASSWORD=password 
      # - HASHED_PASSWORD= 
      - SUDO_PASSWORD=${SUDO_VSC_PASSWORD} 
      # - SUDO_PASSWORD_HASH= 
      # - PROXY_DOMAIN=code-server.my.domain 
      - DEFAULT_WORKSPACE=/var/www 
    volumes:
      - /path/to/appdata/config:/config
      - /srv/www/${APP_NAME}:/var/www
    ports:
      - ${PORT_VSC}:8443
    restart: unless-stopped

networks:
  network-${APP_NAME}:
    external: true
